#Project info 
site_name: Test Amadeus for Developers Test
site_url: https://developers.amadeus.com
site_description: Amadeus for Developers Self-Service APIs Documentation
site_author: Amadeus for Developers

#Repository
repo_name: amadeus4dev/developer-guides
repo_url: https://github.com/minjikarin/developer-guides

#Copyright
copyright: Copyright demo

#Configuration 
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes 
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Amadeus
    code: Source Sans Pro
  favicon: assets/favicon.ico
  logo: assets/logo.svg

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      url_download: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - git-revision-date-localized
  - mkdocs-video

#Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/amadeus4dev
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/cVrFBqx
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/amadeus4dev
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/amadeus-for-developers

#Additional CSS
extra_css:
  - stylesheets/extra.css

#Page tree
nav:
    - Home: index.md
    - Quick start: quick-start.md
    - Pricing: pricing.md
    - Free test data collection: test-data.md
    - API keys:
       - API-Keys/index.md
       - Authorization: API-Keys/authorization.md
       - Production: API-Keys/moving-to-production.md
    - Rate limits: api-rate-limits.md



